version: '3.7'
services:
  notary_frontend:
    container_name: notary-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
    networks:
      lrbsl_net:
        ipv4_address: 172.230.0.1

networks:
  lrbsl_net:
    ipam:
      driver: default
      config:
        - subnet: "172.230.0.0/26"
